name: CI

on:
  workflow_dispatch:

jobs:
  Build_Client:
    runs-on: windows-2022

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup msbuild
        uses: microsoft/setup-msbuild@v2

      - name: Build
        run: |
          cd client\efi-mapper\
          msbuild /t:build kdmapper.sln /p:Configuration="Release" /p:Platform=x64 -maxcpucount:8

      - uses: actions/upload-artifact@v4
        with:
          name: client
          path: |
            *

  Build_Driver:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build
        run: |
          sudo apt install gnu-efi build-essential
          cd driver
          make

      - uses: actions/upload-artifact@v4
        with:
          name: driver
          path: |
            *
